on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_net:
    name: Build check
    runs-on: 'windows-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '4.8.x'

      - name: Restore packages for solution
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore -c Debug
