name: Build check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: 'windows-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore packages for solution
        run: dotnet restore
        working-directory: MicLevelFixer

      - name: Build solution
        run: dotnet build --no-restore -c Debug
        working-directory: MicLevelFixer
