name: Check formatting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: 'windows-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - name: Restore dependencies
        run: dotnet restore
        working-directory: MicLevelFixer

      - name: Check formatting
        run: dotnet format MicLevelFixer.csproj --verify-no-changes --severity error
        working-directory: MicLevelFixer
